const statuses=['想投递','已投递','已测评','已笔试','已一面','已二面','已终面','Offer','已挂','拒绝'];
const statusColors={'想投递':'#b5b0d9','已投递':'#94b8e9','已测评':'#e5be68','已笔试':'#e1a485','已一面':'#9ac5ae','已二面':'#83b9a0','已终面':'#8f9edb','Offer':'#6fb68d','已挂':'#d98d8d','拒绝':'#c5c5ca'};
const seedJobs=[{id:1,company:'小红书',role:'用户产品经理',city:'上海',priority:'梦中情岗',status:'已一面',nextDate:'2026-09-08',url:'',notes:'准备社区产品案例'},{id:2,company:'美团',role:'策略产品经理',city:'北京',priority:'梦中情岗',status:'已测评',nextDate:'2026-09-05',url:'',notes:'测评截止周五'},{id:3,company:'腾讯',role:'产品策划',city:'深圳',priority:'真想去',status:'已投递',nextDate:'',url:'',notes:''},{id:4,company:'网易',role:'游戏运营',city:'杭州',priority:'真想去',status:'想投递',nextDate:'',url:'',notes:''},{id:5,company:'阿里巴巴',role:'商业分析',city:'杭州',priority:'随便投投',status:'已二面',nextDate:'2026-09-12',url:'',notes:'复盘数据分析题'}];
const seedInterviews=[{id:1,jobId:1,date:'2026-09-08',round:'一面',type:'视频面试',note:'重点准备社区增长案例'},{id:2,jobId:5,date:'2026-09-12',round:'二面',type:'视频面试',note:'准备业务理解'}];
let jobs=JSON.parse(localStorage.getItem('recruitment-jobs')||'null')||seedJobs; let interviews=JSON.parse(localStorage.getItem('recruitment-interviews')||'null')||seedInterviews; let tasks=JSON.parse(localStorage.getItem('recruitment-tasks')||'null')||[{id:1,title:'完成美团在线测评',sub:'美团 · 9月5日前',tag:'高优先级',done:false},{id:2,title:'准备小红书一面案例',sub:'小红书 · 9月8日',tag:'面试准备',done:false},{id:3,title:'复盘阿里二面问题',sub:'阿里巴巴 · 9月12日',tag:'复盘',done:false}]; let filter='全部', editingId=null;
const $=s=>document.querySelector(s); const save=()=>{localStorage.setItem('recruitment-jobs',JSON.stringify(jobs));localStorage.setItem('recruitment-interviews',JSON.stringify(interviews));localStorage.setItem('recruitment-tasks',JSON.stringify(tasks));}; const initials=s=>s.slice(0,1); const escapeHtml=s=>(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function render(){renderStats();renderPipeline();renderTasks();renderUpcoming();renderBoard();renderInterviews();renderCalendar();renderQuestions();$('#notes').value=localStorage.getItem('recruitment-notes')||'';}
function renderStats(){let active=jobs.filter(j=>!['拒绝','Offer','已挂'].includes(j.status)).length, interview=jobs.filter(j=>['已一面','已二面','已终面'].includes(j.status)).length;$('#stats-grid').innerHTML=[['已投递',jobs.length,'机会正在积累','var(--purple)'],['进行中',active,'保持推进节奏','var(--blue)'],['面试中',interview,'准备决定表现','var(--peach)'],['Offer',jobs.filter(j=>j.status==='Offer').length,'好消息会发生','var(--mint)']].map(x=>`<div class="stat-card"><span class="stat-label">${x[0]}</span><div class="stat-value">${x[1]}</div><span class="stat-dot" style="background:${x[3]}"></span><span class="stat-foot">${x[2]}</span></div>`).join('')}
function renderPipeline(){let counts=statuses.slice(1,8).map(s=>[s,jobs.filter(j=>j.status===s).length]);let max=Math.max(1,...counts.map(x=>x[1]));$('#pipeline').innerHTML=counts.map(([s,c])=>`<div class="pipeline-row"><span class="label">${s}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(c?10:0,c/max*100)}%;background:${statusColors[s]}"></div></div><span class="count">${c}</span></div>`).join('')}
function renderTasks(){$('#task-list').innerHTML=tasks.map(t=>`<div class="task-item"><div class="check ${t.done?'done':''}" data-task="${t.id}">${t.done?'✓':''}</div><div class="task-main"><strong style="${t.done?'text-decoration:line-through;color:#aaa':''}">${escapeHtml(t.title)}</strong><small>${escapeHtml(t.sub)}</small></div><span class="task-tag" style="background:${t.tag==='高优先级'?'var(--peach)':t.tag==='面试准备'?'var(--blue)':'var(--mint)'}">${t.tag}</span></div>`).join('')||'<div class="empty">还没有待办，先新增一个吧。</div>'}
function renderUpcoming(){$('#upcoming-list').innerHTML=interviews.sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4).map(i=>{let j=jobs.find(x=>x.id===i.jobId)||{};let d=new Date(i.date+'T00:00:00');return `<div class="interview-row"><div class="date-block"><b>${d.getDate()}</b><small>${d.toLocaleDateString('zh-CN',{month:'short'})}</small></div><div class="interview-info"><strong>${escapeHtml(j.company||'未关联企业')} · ${i.round}</strong><p>${escapeHtml(j.role||'')}　${i.type}</p></div></div>`}).join('')||'<div class="empty">暂无面试安排。</div>'}
function renderBoard(){let q=($('#search-input')?.value||'').toLowerCase();let shown=jobs.filter(j=>(filter==='全部'||j.status===filter)&&(`${j.company}${j.role}`.toLowerCase().includes(q)));$('#filter-pills').innerHTML=['全部',...statuses].map(s=>`<button class="filter-pill ${filter===s?'active':''}" data-filter="${s}">${s}</button>`).join('');$('#board').innerHTML=statuses.map(s=>`<div class="board-column"><div class="column-head"><span>${s}</span><span class="column-count">${shown.filter(j=>j.status===s).length}</span></div>${shown.filter(j=>j.status===s).map(j=>`<div class="job-card" data-edit="${j.id}"><div class="job-top"><span class="company-dot">${initials(j.company)}</span><span class="priority-${j.priority==='梦中情岗'?'high':j.priority==='真想去'?'mid':'low'}">●</span></div><h4>${escapeHtml(j.company)}</h4><p>${escapeHtml(j.role)} · ${escapeHtml(j.city)}</p><div class="job-bottom"><div class="job-tags"><span class="enterprise-type-chip enterprise-${enterpriseTypeClass(j)}">${escapeHtml(enterpriseTypeLabel(j))}</span><span class="status-chip intent-${intentClass(j.priority)}">${escapeHtml(j.priority||"未标注")}</span></div>${j.nextDate?`<span class="task-tag">${j.nextDate.slice(5).replace('-','/')}</span>`:''}</div></div>`).join('')||'<div class="empty">暂无岗位</div>'}</div>`).join('')}
function renderInterviews(){$('#all-interviews').innerHTML=interviews.sort((a,b)=>a.date.localeCompare(b.date)).map(i=>{let j=jobs.find(x=>x.id===i.jobId)||{};return `<div class="interview-row"><div class="date-block"><b>${i.date.slice(8)}</b><small>${i.date.slice(0,7)}</small></div><div class="interview-info"><strong>${escapeHtml(j.company||'未关联')} · ${i.round}</strong><p>${escapeHtml(j.role||'')}　${escapeHtml(i.type)}<br>${escapeHtml(i.note||'')}</p></div></div>`}).join('')||'<div class="empty">暂无面试记录。</div>'}
function renderCalendar(){let now=new Date(),y=now.getFullYear(),m=now.getMonth();$('#calendar-month').textContent=`${y} 年 ${m+1} 月`;let first=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();let html='';for(let i=0;i<first;i++)html+='<div class="cal-day muted">·</div>';for(let d=1;d<=last;d++){let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;html+=`<div class="cal-day ${d===now.getDate()?'today ':''}${interviews.some(i=>i.date===ds)?'has-event':''}">${d}</div>`}$('#calendar-grid').innerHTML=html}
function renderQuestions(){$('#question-list').innerHTML=[['请做一下自我介绍','准备 1 分钟版本，突出岗位相关经历'],['为什么选择我们公司？','用业务、岗位、个人成长三个角度回答'],['讲一个你解决复杂问题的经历','STAR 法则：情境、任务、行动、结果'],['你有什么想问我们的？','准备 2-3 个有思考的问题']].map(x=>`<div class="question-item"><strong>${x[0]}</strong><p>${x[1]}</p></div>`).join('')}
function openModal(id=null){editingId=id;let j=jobs.find(x=>x.id===id)||{};$('#modal-title').textContent=id?'编辑岗位':'新增岗位';$('#status-input').innerHTML=statuses.map(s=>`<option ${s===(j.status||'想投递')?'selected':''}>${s}</option>`).join('');let f=$('#job-form');['company','role','city','priority','status','nextDate','url','notes'].forEach(k=>{if(f[k])f[k].value=j[k]||''});$('#modal-backdrop').classList.add('open')}
function closeModal(){$('#modal-backdrop').classList.remove('open');$('#job-form').reset();editingId=null}
document.addEventListener('click',e=>{let nav=e.target.closest('[data-view]');if(nav){document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));nav.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));$(`#${nav.dataset.view}-view`).classList.add('active-view');$('#page-title').textContent=nav.dataset.view==='overview'?'你好，准备出发了吗？':({applications:'岗位追踪',interviews:'秋招日程',prep:'准备中心'}[nav.dataset.view]||'秋招作战台');return}let link=e.target.closest('[data-view-link]');if(link){document.querySelector(`[data-view="${link.dataset.viewLink}"]`).click()}if(e.target.closest('#add-btn, #add-btn-2'))openModal();if(e.target.closest('#close-modal,#cancel-modal'))closeModal();let card=e.target.closest('[data-edit]');if(card)openModal(+card.dataset.edit);let fp=e.target.closest('[data-filter]');if(fp){filter=fp.dataset.filter;renderBoard()}let check=e.target.closest('[data-task]');if(check){let t=tasks.find(t=>t.id==check.dataset.task);t.done=!t.done;save();renderTasks()}if(e.target.closest('#clear-notes')){$('#notes').value='';localStorage.removeItem('recruitment-notes');showToast('笔记已清空')}});
$('#job-form').addEventListener('submit',e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.target));if(editingId)jobs=jobs.map(j=>j.id===editingId?{...j,...data}:j);else {data.status=(data.status||'想投递').trim();data.company=data.company.trim();data.role=data.role.trim();jobs.push({id:Date.now(),...data});}save();closeModal();filter='全部';render();showToast(editingId?'岗位已更新':'岗位已添加')});$('#search-input').addEventListener('input',renderBoard);$('#notes').addEventListener('input',()=>{localStorage.setItem('recruitment-notes',$('#notes').value);$('#note-saved').textContent='刚刚保存'});$('#quick-prep-btn').addEventListener('click',()=>showToast('快速准备清单已就绪：自我介绍 · 项目案例 · 反问问题'));$('#add-task-btn').addEventListener('click',()=>{let title=prompt('想添加什么待办？');if(title){tasks.push({id:Date.now(),title,sub:'个人待办',tag:'准备',done:false});save();renderTasks();showToast('待办已添加')}});$('#add-interview-btn').addEventListener('click',()=>showToast('面试记录功能将在下一步开放，你可以先在岗位卡片中记录日期。'));function showToast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}render();
function enterpriseTypeLabel(job){const value=(job&&job.enterpriseType||'').trim();if(['国企','央企','事业单位','国央企'].includes(value))return '国央企';if(value==='外企')return '外企';if(value==='私企'||value==='民营企业')return '私企';return '未标注'}function enterpriseTypeClass(job){const type=enterpriseTypeLabel(job);return type==='国央企'?'state-owned':type==='外企'?'foreign':type==='私企'?'private':'unknown'}
function intentClass(value){return value==='梦中情岗'?'dream':value==='真想去'?'wanted':value==='可以去'?'okay':value==='随便投投'?'casual':'unknown'}