(function(){
  let selectedDate=null;
  function today(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
  function allItems(){
    const dates=window.recruitmentEvents?window.recruitmentEvents.get():[];
    const records=(typeof interviews!=='undefined'?interviews:[]).map(i=>{const job=(typeof jobs!=='undefined'?jobs:[]).find(j=>j.id===i.jobId)||{};return{id:i.id,date:i.date,title:(job.company||'\u672a\u5173\u8054\u4f01\u4e1a')+' · '+(i.round||'\u9762\u8bd5'),source:'interview'}});
    return records.concat(dates.map(x=>{const job=(typeof jobs!=='undefined'?jobs:[]).find(j=>j.id===Number(x.jobId));return{id:x.id,date:x.date,title:job?job.company+(job.role?' · '+job.role:'')+' · '+(x.title||x.type):x.title,source:'event'}})).sort((a,b)=>{const now=today(),af=a.date>=now,bf=b.date>=now;if(af!==bf)return af?-1:1;return af?a.date.localeCompare(b.date):b.date.localeCompare(a.date)});
  }
  function renderTimeline(){
    const list=$('#all-interviews');if(!list)return;const now=today(),all=allItems(),items=selectedDate?all.filter(x=>x.date===selectedDate):all;const heading=list.parentElement.querySelector('.panel-head h3');if(heading)heading.textContent=selectedDate?Number(selectedDate.slice(5,7))+'月'+Number(selectedDate.slice(8))+'日事件':'全部事件';if(backButton)backButton.hidden=!selectedDate;document.querySelectorAll('#calendar-grid .cal-day').forEach(day=>day.classList.remove('timeline-selected'));if(selectedDate){const month=$('#calendar-month').textContent.match(/(\d+)\s*年\s*(\d+)\s*月/);if(month&&Number(month[1])===Number(selectedDate.slice(0,4))&&Number(month[2])===Number(selectedDate.slice(5,7))){document.querySelectorAll('#calendar-grid .cal-day').forEach(day=>{if(Number(day.textContent)===Number(selectedDate.slice(8)))day.classList.add('timeline-selected')})}}
    list.innerHTML=items.length?items.map(x=>{const d=x.date.split('-');return '<div class="timeline-item '+(x.date<now?'is-past':'')+'" data-schedule-kind="'+x.source+'" data-schedule-id="'+x.id+'"><div class="timeline-date"><b>'+d[2]+'</b><small>'+d[0]+'-'+d[1]+'</small></div><div class="timeline-main"><strong>'+escapeHtml(x.title)+'</strong></div><span class="timeline-edit-hint">›</span></div>'}).join(''):'<div class="detail-empty">'+(selectedDate?'\u5f53\u5929\u6682\u65e0\u4e8b\u4ef6\u3002':'\u8fd8\u6ca1\u6709\u9762\u8bd5\u6216\u91cd\u8981\u65f6\u95f4\u8282\u70b9\u3002')+'</div>';
  }
  function closeEventEditor(){document.querySelector('#schedule-event-editor')?.remove()}
  function openEventEditor(id){
    const events=window.recruitmentEvents?window.recruitmentEvents.get():[],record=events.find(x=>x.id===Number(id));if(!record)return;
    closeEventEditor();const box=document.createElement('div');box.id='schedule-event-editor';box.className='schedule-editor-backdrop';
    box.innerHTML='<div class="schedule-editor"><div class="schedule-editor-head"><h3>\u7f16\u8f91\u65f6\u95f4\u8282\u70b9</h3><button type="button" class="schedule-editor-close">×</button></div><form><label>\u4e8b\u9879\u540d\u79f0<input name="title" required></label><div class="form-grid"><label>\u65e5\u671f<input name="date" type="date" required></label><label>\u7c7b\u578b<select name="type"><option>\u62a5\u540d\u622a\u6b62</option><option>\u7b14\u8bd5</option><option>\u6d4b\u8bc4</option><option>\u5ba3\u8bb2\u4f1a</option><option>\u5176\u4ed6</option></select></label><label>\u91cd\u8981\u7a0b\u5ea6<select name="priority"><option>\u91cd\u8981</option><option>\u666e\u901a</option></select></label></div><label>\u5907\u6ce8<textarea name="note" placeholder="\u62a5\u540d\u7f51\u5740\u3001\u6750\u6599\u6e05\u5355\u3001\u6ce8\u610f\u4e8b\u9879\u2026\u2026"></textarea></label><div class="schedule-editor-actions"><button type="button" class="text-btn schedule-editor-delete">\u5220\u9664</button><span></span><button type="button" class="secondary-btn schedule-editor-cancel">\u53d6\u6d88</button><button class="primary-btn" type="submit">\u4fdd\u5b58</button></div></form></div>';
    document.body.appendChild(box);const form=box.querySelector('form'),linkLabel=document.createElement('label');linkLabel.innerHTML='\u5173\u8054\u5c97\u4f4d<select name="jobId"><option value="">\u8bf7\u9009\u62e9\u5c97\u4f4d</option></select>';form.elements.note.closest('label').before(linkLabel);form.elements.jobId.innerHTML='<option value="">\u8bf7\u9009\u62e9\u5c97\u4f4d</option>'+jobs.map(j=>'<option value="'+j.id+'">'+escapeHtml(j.company)+(j.role?' · '+escapeHtml(j.role):'')+'</option>').join('');function toggleLink(){linkLabel.hidden=!['\u6d4b\u8bc4','\u7b14\u8bd5'].includes(form.elements.type.value)}['title','date','type','priority','note','jobId'].forEach(k=>{if(form[k])form[k].value=record[k]||''});toggleLink();form.elements.type.addEventListener('change',toggleLink);
    const close=closeEventEditor;box.querySelector('.schedule-editor-close').onclick=close;box.querySelector('.schedule-editor-cancel').onclick=close;box.onclick=e=>{if(e.target===box)close()};
    form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));data.jobId=['\u6d4b\u8bc4','\u7b14\u8bd5'].includes(data.type)&&data.jobId?Number(data.jobId):null;Object.assign(record,data);window.recruitmentEvents.save();close();renderTimeline();if(typeof renderCalendarMonth==='function')renderCalendarMonth();showToast('\u65f6\u95f4\u8282\u70b9\u5df2\u66f4\u65b0')};
    box.querySelector('.schedule-editor-delete').onclick=()=>{if(!confirm('\u786e\u5b9a\u5220\u9664\u8fd9\u4e2a\u65f6\u95f4\u8282\u70b9\u5417\uff1f'))return;events.splice(events.indexOf(record),1);window.recruitmentEvents.save();close();renderTimeline();if(typeof renderCalendarMonth==='function')renderCalendarMonth();showToast('\u65f6\u95f4\u8282\u70b9\u5df2\u5220\u9664')};
  }
  const panelHead=$('#all-interviews')?.parentElement?.querySelector('.panel-head'),head=panelHead?.querySelector('h3'),backButton=document.createElement('button');backButton.type='button';backButton.className='timeline-back';backButton.textContent='\u2190 \u8fd4\u56de\u5168\u90e8';backButton.hidden=true;if(panelHead)panelHead.appendChild(backButton);backButton.onclick=()=>{selectedDate=null;renderTimeline()};if(head)head.textContent='\u5168\u90e8\u4e8b\u4ef6';
  const style=document.createElement('style');style.textContent='.independent-events{display:none!important}.timeline-item{display:flex;align-items:center;gap:14px;padding:15px 0;border-bottom:1px solid #f0f0f3;cursor:pointer;transition:.18s}.timeline-item:hover{padding-left:6px;background:#faf9ff}.timeline-item.is-past{opacity:.55}.timeline-date{width:50px;height:50px;flex:0 0 50px;border-radius:12px;background:#f1efff;color:#7161e8;display:grid;place-content:center;text-align:center}.timeline-date b{font-size:19px;line-height:1}.timeline-date small{font-size:9px;margin-top:3px}.timeline-main{flex:1;min-width:0}.timeline-main strong{font-size:13px}.timeline-edit-hint{color:#bbb;font-size:22px}.schedule-editor-backdrop{position:fixed;inset:0;z-index:1200;display:flex;align-items:center;justify-content:center;padding:20px;background:#231f4366}.schedule-editor{width:min(520px,calc(100vw - 40px));max-height:calc(100vh - 40px);overflow:auto;box-sizing:border-box;padding:22px;border-radius:16px;background:#fff;box-shadow:0 20px 60px #28235a33}.schedule-editor-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.schedule-editor-head h3{margin:0}.schedule-editor-close{border:0;background:transparent;color:#999;font-size:24px;cursor:pointer}.schedule-editor label{display:block;margin-bottom:13px;color:#777;font-size:12px}.schedule-editor input,.schedule-editor select,.schedule-editor textarea{display:block;width:100%;box-sizing:border-box;margin-top:6px;padding:10px;border:1px solid #e7e5f1;border-radius:8px;outline:0;font:13px inherit}.schedule-editor textarea{min-height:100px;resize:vertical}.schedule-editor-actions{display:grid;grid-template-columns:auto 1fr auto auto;align-items:center;gap:10px;margin-top:16px}.schedule-editor-delete{color:#cf6666}@media(max-width:600px){.timeline-item{gap:9px}.schedule-editor .form-grid{grid-template-columns:1fr}}';document.head.appendChild(style);const filterStyle=document.createElement('style');filterStyle.textContent='.timeline-back{border:0;background:#f3f1ff;color:#6658dc;border-radius:8px;padding:7px 10px;font:600 11px inherit;cursor:pointer}.timeline-back[hidden]{display:none}.cal-day.timeline-selected{background:#7161e8;color:#fff;font-weight:700}';document.head.appendChild(filterStyle);
  document.addEventListener('click',e=>{const day=e.target.closest('#calendar-grid .cal-day');if(day&&/^\\d+$/.test(day.textContent.trim())){const month=$('#calendar-month').textContent.match(/(\\d+)\\s*年\\s*(\\d+)\\s*月/);if(month){selectedDate=month[1]+'-'+String(month[2]).padStart(2,'0')+'-'+String(day.textContent.trim()).padStart(2,'0');renderTimeline()}return}if(e.target.closest('.calendar-title button')){selectedDate=null;setTimeout(renderTimeline,0);return}const item=e.target.closest('.timeline-item[data-schedule-kind]');if(!item)return;if(item.dataset.scheduleKind==='event')openEventEditor(item.dataset.scheduleId);else if(typeof editInterview==='function')editInterview(Number(item.dataset.scheduleId))});
  document.addEventListener('click',e=>{const day=e.target.closest('#calendar-grid .cal-day');if(!day)return;const dayNumber=Number(day.textContent.trim()),parts=$('#calendar-month').textContent.match(/[0-9]+/g);if(Number.isInteger(dayNumber)&&dayNumber>0&&parts&&parts.length>=2){selectedDate=parts[0]+'-'+String(parts[1]).padStart(2,'0')+'-'+String(dayNumber).padStart(2,'0');renderTimeline()}},true);
  renderTimeline();setInterval(renderTimeline,600);
})();